### ISSUE TITLE
:'v:bind-for' => 'id'

### ISSUE THREAD

**Issue by betabong** [Kosai106/vscode-ruby-syntax-replacer#2]
If you add these regex, you should be able to catch those fancier cases too:
`/([^:]|^):('[\w\-:]+')\s?(\s*)=>\s?(\s*)/g`
`/([^:]|^):("[\w\-:]+")\s?(\s*)=>\s?(\s*)/g`

I do think that this is still incomplete. Probably a quoted symbol can contain practically every kind of string:

`/([^:]|^):('[^']+')\s?(\s*)=>\s?(\s*)/g`
`/([^:]|^):("[^"]+")\s?(\s*)=>\s?(\s*)/g`

**Comment by Kosai106** [comment]
I see what you're going for, but the current Regex is already catching these cases as far as I can tell.

Try the current Regex, versus yours on this [example](https://www.regexpal.com/?).

**Comment by betabong** [comment]
The regex covers many cases, but not some rare ones like:
`%p{:'v-bind:class' => 'goes', :'even!#more' => 'things'}`

I know it's not common, but still it would be nice to cover all cases.

**Comment by Kosai106** [comment]
Covering all cases will be close to impossible.

That being said, I've updated the extension to cover a few additional cases.
