### ISSUE TITLE
The extension doesn't work with ".html.erb" files

### ISSUE THREAD

**Issue by vadim-96** [Kosai106/vscode-ruby-syntax-replacer#3]
For example in ".html.erb" file:
`<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>`
does not convert to:
`<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>`

**Comment by Kosai106** [comment]
This should now be working. I've added support for `.html.erb` and `.html.haml` files.
