### ISSUE TITLE
"Problems" tab showing invalid issues with HAML files

### ISSUE THREAD

**Issue by simmerz** [Kosai106/vscode-ruby-syntax-replacer#5]
Does the extension add syntax highlighting and linting somehow? On enabling the extension, I get invalid linting errors. I've narrowed it down to this extension being the trigger.

Before:
<img width="1017" alt="Screenshot 2019-05-14 at 10 41 58" src="https://user-images.githubusercontent.com/24327/57688364-28b7f700-7635-11e9-91cb-fdfffdc2f7b6.png">

After:
<img width="1277" alt="Screenshot 2019-05-14 at 10 42 11" src="https://user-images.githubusercontent.com/24327/57688369-2e154180-7635-11e9-92b7-3ecfffdbcf9e.png">

**Comment by Kosai106** [comment]
I'm sorry, but I don't know what could possibly be causing this - This extension does not lint your code.
